// Pruebas de integración reales. Ejecutar únicamente sobre una base de pruebas.
// Generan usuarios y registros identificados por UUID; solo eliminan lógicamente sus misiones de prueba.
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';

const url = (process.env.TEST_API_URL || 'http://localhost:8080').replace(/\/$/, '');
const email = process.env.TEST_ADMIN_EMAIL;
const password = process.env.TEST_ADMIN_PASSWORD;
if (!email || !password) throw new Error('Configura TEST_ADMIN_EMAIL y TEST_ADMIN_PASSWORD para una API local de pruebas.');
let checks = 0;
const verify = (condition, message) => { assert.ok(condition, message); checks++; };
async function call(action, data = {}, token, expected = 200, file) {
  if (action === 'missions.create' || action === 'missions.update') data = { minimumRankCode:'POSTULANTE',evidenceRequirement:'Archivo verificable',missionType:'FORMATIVA', ...data };
  if (action === 'submissions.create') data = { respectConfirmed:true,privacyConfirmed:true,occurredAt:new Date().toISOString(),submissionNote:expected === 400 ? '' : 'Bitácora detallada de la actividad realizada con respeto.', ...data };
  if (action === 'submissions.review') data = { requirementsVerified:true, ...data };
  const headers = token ? { Authorization: `Bearer ${token}` } : {};
  let body;
  if (file) {
    body = new FormData();
    body.append('action', action);
    body.append('data', JSON.stringify(data));
    body.append('file', file, 'proof.png');
  } else {
    headers['Content-Type'] = 'application/json';
    body = JSON.stringify({ action, data });
  }
  const response = await fetch(`${url}/api`, { method: 'POST', headers, body });
  const result = await response.json();
  assert.equal(response.status, expected, `${action}: ${JSON.stringify(result)}`);
  checks++;
  return result;
}
const run = randomUUID();
const userPassword = `Test-${run}!`;
const png = new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j8H0AAAAASUVORK5CYII=', 'base64')], { type: 'image/png' });
verify((await fetch(`${url}/healthz`)).ok, 'Health de API y PostgreSQL');
await call('auth.me', {}, undefined, 401);
await call('invented.action', {}, undefined, 400);
const invalidJson = await fetch(`${url}/api`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{' });
verify(invalidJson.status === 400, 'JSON inválido');
const preflight = await fetch(`${url}/api`, { method:'OPTIONS', headers: { Origin:'http://localhost:5173', 'Access-Control-Request-Method':'POST', 'Access-Control-Request-Headers':'content-type,authorization' } });
verify(preflight.headers.get('access-control-allow-origin') === 'http://localhost:5173', 'CORS permitido');
const deniedCors = await fetch(`${url}/api`, { method:'OPTIONS', headers: { Origin:'https://untrusted.example', 'Access-Control-Request-Method':'POST' } });
verify(!deniedCors.headers.has('access-control-allow-origin'), 'CORS restringido');
await call('auth.login', { email, password: 'incorrect' }, undefined, 401);
const admin = await call('auth.login', { email, password });
verify(admin.user.role === 'SUPER_ADMIN' && !JSON.stringify(admin.user).includes('password'), 'Administrador sin exponer contraseña');
const at = admin.accessToken;
// El mismo flujo que usa el formulario de registro: certificado y cuenta atómicos.
const atomicEmail = `atomic-${run}@example.com`;
const atomicData = { email:atomicEmail,password:userPassword,fullName:'Titular atómico',activationMode:'NUMBER',certificateNumber:`ATOMIC-${run}` };
await call('auth.register',atomicData,undefined,409);
await call('auth.login',{email:atomicEmail,password:userPassword},undefined,401);
await call('certificates.create',{certificateNumber:`ATOMIC-${run}`,issuedToEmail:atomicEmail},at);
const atomicUser = await call('auth.register',atomicData);
verify(atomicUser.user.role === 'SOLDADO_ACTIVE','Registro y certificado en una transacción');
const atomicReviewEmail = `atomic-review-${run}@example.com`;
const atomicReviewData = { email:atomicReviewEmail,password:userPassword,fullName:'Revisión atómica',activationMode:'REVIEW',certificateNumber:'S/N' };
await call('auth.register',atomicReviewData,undefined,400,new Blob(['bad'],{type:'image/png'}));
const atomicReviewUser = await call('auth.register',atomicReviewData,undefined,200,png);
verify(atomicReviewUser.user.role === 'SOLDADO_PENDING','Registro y archivo en una transacción');
await call('auth.register', { email:'bad', password:userPassword, fullName:'Test' },undefined,400);
await call('auth.register', { email:`short-${run}@example.com`, password:'short', fullName:'Test' },undefined,400);
const userEmail = `${run}@example.com`;
const user = await call('auth.register', { email:userEmail, password:userPassword, fullName:`Prueba ${run}` });
const ut = user.accessToken;
verify(user.user.role === 'SOLDADO_PENDING', 'Registro pendiente');
await call('auth.register', { email:userEmail.toUpperCase(), password:userPassword, fullName:'Duplicado' },undefined,409);
await call('users.list', {},ut,403);
await call('missions.list', {},ut,403);
await call('users.activate', { id:admin.user.id },at,400);
await call('certificates.list', { page:0 },at,400);
await call('users.list', { role:"x' OR 1=1--" },at,400);
const cert = await call('certificates.create', { certificateNumber:`TEST-${run}`, issuedToName:`Prueba ${run}`, issuedToEmail:userEmail },at);
await call('certificates.create', { certificateNumber:`test-${run}` },at,409);
await call('activation.claim', { certificateNumber:'NONEXISTENT' },ut,409);
const activated = await call('activation.claim', { certificateNumber:`test-${run}` },ut);
verify(activated.user.role === 'SOLDADO_ACTIVE', 'Activación con certificado');
verify((await call('auth.me', {},ut)).role === 'SOLDADO_ACTIVE', 'Rol actualizado sin reemitir token');
await call('profile.update',{birthDate:'1990-01-01'},ut);
const certificateList = await call('certificates.list', { pageSize:100 },at);
verify(certificateList.items.find(c => c.id === cert.id)?.isUsed, 'Certificado consumido');
const outsider = await call('auth.register', { email:`outsider-${run}@example.com`,password:userPassword,fullName:'Otro titular' });
await call('activation.claim', { certificateNumber:`TEST-${run}` },outsider.accessToken,409);
const mismatched = await call('certificates.create', { certificateNumber:`OWNER-${run}`,issuedToEmail:'other@example.com' },at);
await call('activation.claim', { certificateNumber:mismatched.certificateNumber },outsider.accessToken,409);
await call('activation.submit', { certificateNumber:'S/N' },outsider.accessToken,400,new Blob(['not-a-png'],{type:'image/png'}));
const review = await call('activation.submit', { certificateNumber:'S/N' },outsider.accessToken,200,png);
await call('activation.submit', { certificateNumber:'S/N' },outsider.accessToken,409,png);
const pending = await call('users.list', { role:'SOLDADO_PENDING',pageSize:100 },at);
const pendingUser = pending.items.find(u => u.id === outsider.user.id);
verify(!!pendingUser?.certificateFileId, 'Archivo visible para la revisión');
await call('files.get', { id:pendingUser.certificateFileId },ut,404);
const file = await call('files.get', { id:pendingUser.certificateFileId },at);
verify(file.contentType === 'image/png' && !!file.base64, 'Archivo persistente y protegido');
await call('certificateReviews.review', { id:review.id,status:'APPROVED' },at);
await call('certificateReviews.review', { id:review.id,status:'APPROVED' },at,409);
verify((await call('auth.me', {},outsider.accessToken)).role === 'SOLDADO_ACTIVE', 'Aprobación manual');
await call('missions.create', { title:'Unauthorized',description:'x' },ut,403);
await call('missions.create', { title:'Bad type',description:'x',missionType:'INVALID' },at,400);
const mission = await call('missions.create', { title:`Misión ${run}`,description:'Prueba de integración',badgeWeight:3 },at);
verify(mission.publicationState === 'DRAFT', 'Misión en borrador');
await call('missions.assign', { id:mission.id },ut,404);
await call('submissions.create', { missionId:mission.id },ut,404,png);
await call('missions.update', { id:mission.id,title:`Misión actualizada ${run}`,description:'Prueba de integración',badgeWeight:3 },at);
await call('missions.publish', { id:mission.id },at);
await call('missions.update', { id:mission.id,title:'Bad',description:'x' },at,409);
await call('submissions.create', { missionId:mission.id },ut,409,png);
const restrictedMission = await call('missions.create',{title:'Misión de rango superior',description:'Prueba de rango para asignación',minimumRankCode:'SARGENTO_ARMAS'},at);
await call('missions.publish',{id:restrictedMission.id},at);
await call('missions.assign',{id:restrictedMission.id},ut,403);
await call('missions.archive',{id:restrictedMission.id},at);
const [assignment, concurrentAssignment] = await Promise.all([
  call('missions.assign', { id:mission.id },ut),
  call('missions.assign', { id:mission.id },ut),
]);
verify(assignment.id === concurrentAssignment.id,'Asignaciones concurrentes sin duplicados');
verify(assignment.status === 'ASSIGNED' && !assignment.fileId,'Asignación sin archivo');
const repeatedAssignment = await call('missions.assign', { id:mission.id },ut);
verify(repeatedAssignment.id === assignment.id,'Reintentar asignación no la duplica');
const myAssignments = await call('assignments.list',{missionId:mission.id},ut);
verify(myAssignments.total === 1 && myAssignments.items[0].id === assignment.id,'Asignación persistida');
verify((await call('missions.list',{},ut)).items.find(m=>m.id===mission.id)?.myAssignment?.status === 'ASSIGNED','Listado restaura el estado para subir después');
const anotherSession = await call('auth.login',{email:userEmail,password:userPassword});
verify((await call('missions.list',{},anotherSession.accessToken)).items.find(m=>m.id===mission.id)?.myAssignment?.status === 'ASSIGNED','Asignación conservada en una nueva sesión');
await call('submissions.create',{missionId:mission.id},ut,400);
verify((await call('assignments.list',{missionId:mission.id},outsider.accessToken)).total === 0,'Asignaciones privadas del soldado');
await call('submissions.list',{},ut,403);
const submission = await call('submissions.create', { missionId:mission.id,submissionNote:'Prueba' },ut,200,png);
verify(!('fileId' in submission) && !('submissionNote' in submission),'Soldado recibe estado sin evidencia');
const adminSubmissions = await call('submissions.list',{missionId:mission.id},at);
const proofId = adminSubmissions.items.find(s=>s.id===submission.id).fileId;
await call('files.get',{id:proofId},ut,404);
await call('files.get',{id:proofId},outsider.accessToken,404);
verify((await call('files.get',{id:proofId},at)).contentType === 'image/png','Administrador puede consultar evidencia real');
verify((await call('missions.list',{},ut)).items.find(m=>m.id===mission.id)?.myAssignment?.status === 'PENDING','Estado actualizado tras subir evidencia');
await call('submissions.create', { missionId:mission.id },ut,409,png);
await call('submissions.review', { id:submission.id,status:'APPROVED' },ut,403);
await call('submissions.review', { id:submission.id,status:'REJECTED',reviewNote:'Adjunta otra evidencia' },at);
const resubmitted = await call('submissions.create', { missionId:mission.id },ut,200,png);
verify(resubmitted.id !== submission.id, 'Corrección conserva el reporte rechazado para auditoría');
const concurrentReview = await Promise.all([1,2].map(async () => {
  const response = await fetch(`${url}/api`, { method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${at}`},body:JSON.stringify({action:'submissions.review',data:{id:resubmitted.id,status:'APPROVED',requirementsVerified:true}}) });
  return response.status;
}));
verify(concurrentReview.sort().join(',') === '200,409', 'Aprobación concurrente contabilizada una sola vez');
const progress = await call('progress.get', {},ut);
verify(progress.totalPoints === 3 && progress.rankCode === 'POSTULANTE', 'Los puntos solos no conceden rango sin ingreso e hito');
verify((await call('history.get', {},ut)).completedMissionTotal === 1, 'Historial sin duplicados');
verify((await call('history.get',{},ut)).history.items.every(s=>!('fileId' in s) && !('submissionNote' in s)),'Historial del soldado no revela evidencias');
const members = await call('members.list', {},ut);
verify(!members.items.some(u => u.email || u.passwordHash), 'Directorio sin correos privados');
const report = await call('sectReports.create', { sectName:`Reporte ${run}`,locationDescription:'Zona de prueba',referenceNote:'Reporte de integración' },ut);
const ownReports = await call('sectReports.list', {},ut);
verify(ownReports.items.some(r => r.id === report.id), 'Reportes propios');
const otherReports = await call('sectReports.list', {},outsider.accessToken);
verify(!otherReports.items.some(r => r.id === report.id), 'Privacidad de reportes sin aprobar');
await call('sectReports.review', { id:report.id,status:'APPROVED' },at);
await call('sectReports.review', { id:report.id,status:'APPROVED' },at,409);
verify((await call('sectRegistry.list', {},ut)).items.some(r => r.id === report.id), 'Registro moderado');
const overview = await call('overview.get', {},at);
verify(typeof overview.missionSubmissions.pendingCount === 'number', 'Dashboard conectado');
await call('overview.get', {},ut,403);
await call('missions.archive', { id:mission.id },at);
await call('missions.assign', { id:mission.id },outsider.accessToken,404);
await call('submissions.create', { missionId:mission.id },outsider.accessToken,404,png);
await call('missions.delete', { id:mission.id },ut,403);
const beforeDelete = await call('missions.list', { pageSize:100 },at);
const deleted = await call('missions.delete', { id:mission.id },at);
verify(deleted.id === mission.id && deleted.deleted === true, 'Administrador elimina misión archivada');
const afterDelete = await call('missions.list', { pageSize:100 },at);
verify(afterDelete.total === beforeDelete.total - 1 && !afterDelete.items.some(m => m.id === mission.id), 'Misión eliminada fuera del catálogo administrador y su total');
verify(!(await call('missions.list', { pageSize:100 },ut)).items.some(m => m.id === mission.id), 'Misión eliminada fuera del catálogo soldado');
await call('missions.delete', { id:mission.id },at,404);
await call('missions.delete', { id:randomUUID() },at,404);
await call('missions.publish', { id:mission.id },at,409);
await call('missions.archive', { id:mission.id },at,409);
await call('missions.assign', { id:mission.id },ut,404);
await call('submissions.create', { missionId:mission.id },ut,404,png);
verify((await call('progress.get', {},ut)).totalPoints === progress.totalPoints, 'Eliminar conserva los puntos obtenidos');
verify((await call('history.get', {},ut)).completedMissionTotal === 1, 'Eliminar conserva las misiones completadas');
verify((await call('assignments.list', { missionId:mission.id },ut)).total === 1, 'Eliminar conserva asignaciones históricas');
verify((await call('files.get', { id:proofId },at)).contentType === 'image/png', 'Eliminar conserva evidencias para auditoría');
const deleteDraft = await call('missions.create', { title:`Borrador a eliminar ${run}`,description:'Prueba de eliminación' },at);
await call('missions.delete', { id:deleteDraft.id },at);
await call('missions.update', { id:deleteDraft.id,title:'No revivir',description:'Prueba' },at,409);
const deletePublished = await call('missions.create', { title:`Publicada a eliminar ${run}`,description:'Prueba de eliminación' },at);
await call('missions.publish', { id:deletePublished.id },at);
await call('missions.assign', { id:deletePublished.id },ut);
const pendingDeletion = await call('submissions.create', { missionId:deletePublished.id },ut,200,png);
await call('missions.delete', { id:deletePublished.id },at);
await call('submissions.create', { missionId:deletePublished.id },ut,404,png);
verify((await call('submissions.list', { missionId:deletePublished.id },at)).items.some(s => s.id === pendingDeletion.id), 'Eliminar conserva reportes pendientes');
await call('submissions.review', { id:pendingDeletion.id,status:'REJECTED',reviewNote:'Misión retirada del catálogo' },at);
await call('users.setRole', { id:outsider.user.id,role:'REGISTRADOR' },at);
const registradorMission = await call('missions.create', { title:`Registrador elimina ${run}`,description:'Prueba de permiso' },at);
await call('missions.delete', { id:registradorMission.id },outsider.accessToken);
await call('users.setRole', { id:user.user.id,role:'REGISTRADOR' },outsider.accessToken,403);
await call('users.deactivate', { id:outsider.user.id },at,403);
await call('users.setRole', { id:outsider.user.id,role:'SOLDADO_ACTIVE' },at);
await call('users.deactivate', { id:outsider.user.id },at);
await call('auth.me', {},outsider.accessToken,401);
await call('auth.login', { email:`outsider-${run}@example.com`,password:userPassword },undefined,403);
await call('auth.logout', {},ut);
await call('auth.me', {},ut,401);
const limiterEmail = `ratelimit-${run}@example.com`;
for (let i=0;i<10;i++) await call('auth.login', { email:limiterEmail,password:'incorrect' },undefined,401);
await call('auth.login', { email:limiterEmail,password:'incorrect' },undefined,429);
console.log(`OK: ${checks} verificaciones de integración (run ${run}).`);
